env:
  - DB_USERNAME=user DB_PASSWORD=password DB_URL=jdbc:mysql://127.0.0.1/test;

#Travis install phase executes mvn test, which fires the mvn sql plugin execution.
#You need a database created before the Travis install phase (see the before_install below).
#Be aware that by default, travis seems to use a username of vagrant that is not an admin on the database and cant grant permission.
#Override this by specifying the user/password when executing a command. Don't use the shortened password -p command.

before_install:
    - mysql --user=root --password= -e 'create database if not exists test;'
    - mysql --user=root --password= -e "CREATE USER 'user'@'%' IDENTIFIED BY 'password';"
    - mysql --user=root --password= -e 'select User from mysql.user;'
    - mysql --user=root --password= -e "grant all on test.* to 'user'@'%' identified by 'password';"



language: groovy

script:
    - mvn -q clean verify

branches:
  only:
    - master